### ISSUE TITLE
feat: implement the new changes proposed by protocol

### ISSUE THREAD

**Issue by Hoyoe** [vrn-deco/cli#11]
Should implement the new changes proposed by vrn-deco/boilerplate#109

## Affected Scope

- @vrn-deco/cli-command-boilerplate

**Comment by Cphayim** [comment]
#12 
Implements passing additional parameters when calling the runner

**Comment by Cphayim** [comment]
#16 
- Implemented `Lang` and `Boilerplate` support for new protocols in interactive mode selection
- Highlight `recommended` and `deprecated`
- Optimized `tags` display
