### ISSUE TITLE
npm query failed, unable check updates and fetch manifest

### ISSUE THREAD

**Issue by Hoyoe** [vrn-deco/cli#15]
<img width="581" alt="image" src="https://user-images.githubusercontent.com/37341254/160296217-cfbd0e3d-100d-42ce-ad52-61711690f545.png">

**Comment by Hoyoe** [comment]
It seems to be a problem with the Taobao npm mirror registry, and the query interface reports an error

`https://registry.npmmirror.com/@vrn-deco/cli` got 500: 
```
$ wget https://registry.npmmirror.com/@vrn-deco/cli
--2022-03-28 02:53:45--  https://registry.npmmirror.com/@vrn-deco/cli
正在解析主机 registry.npmmirror.com (registry.npmmirror.com)... 240e:978:306:6:3::3f3, 61.160.228.8
正在连接 registry.npmmirror.com (registry.npmmirror.com)|240e:978:306:6:3::3f3|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2022-03-28 02:54:36 错误 500：Internal Server Error。
```


`https://registry.npmjs.com/@vrn-deco/cli` is normal
```
$ wget https://registry.npmjs.com/@vrn-deco/cli
--2022-03-28 02:54:39--  https://registry.npmjs.com/@vrn-deco/cli
正在解析主机 registry.npmjs.com (registry.npmjs.com)... 2606:4700::6810:1923, 2606:4700::6810:1423, 2606:4700::6810:1023, ...
正在连接 registry.npmjs.com (registry.npmjs.com)|2606:4700::6810:1923|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度：68866 (67K) [application/json]
```

**Comment by Hoyoe** [comment]
1. Should we consider changing the default of `NPMRegistry` back to `npm`
2. When something goes wrong, I want to replace the `NPMRegistry` with the `vrn config` command, but I have to wait for the request to time out or fail. An option can be added to skip checking updates

**Comment by Cphayim** [comment]
> 1. Should we consider changing the default of `NPMRegistry` back to `npm`
> 2. When something goes wrong, I want to replace the `NPMRegistry` with the `vrn config` command, but I have to wait for the request to time out or fail. An option can be added to skip checking updates

可能他们在维护吧。。。现在已经正常了😂

1. 这个情况应该是偶尔发生的，个人建议还是保留 Taobao  源的默认值，可以考虑在 `cli-npm-helper` 包的统一查询点做一下失败回退到 NPM 源查询
2. 这个提议不错，可以添加一个全局选项（或者环境变量）来强制组织更新检查。另外我有打算把更新检查操作从 `prepare` 阶段下沉到 `Command::init` 之前，这样可以让一些没必要执行更新检查的命令跳过检查 （例如：`version`, `config`）

我先记录一下👌
